# Change PREFIX key to Control-a
unbind C-b
set-option -g prefix C-a

# Split panels with | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Enable Tmux Powerline
run-shell "powerline-daemon -q"
source /usr/share/tmux/powerline.conf

# Improvements made by Neovim :healthcheck command
set-option -sg escape-time 10
set-option -g default-terminal "tmux-256color"
