# Env variables
export DOTFILES=~/Repos/Personal/dotfiles
export EDITOR=nvim

# Aliases
alias ll="exa -la"
alias ls="exa"
alias gotodf="cd $DOTFILES"
alias gitrdp="cd ~/Repos/Personal"
alias gitrdw="cd ~/Repos/Work"
