# exec this file with "make"

install: omni-gnome-terminal homebrew docker zsh 

omni-gnome-terminal:
	./omni-gnome-terminal.sh

zsh:
	./setup-zsh.sh

docker:
	./setup-docker.sh

homebrew:
	./install-brew.sh
